export enum EventTypeEnum {
    CHANGE_DISPLAY_NAME = 'CHANGE_DISPLAY_NAME',
    CHANGE_ROLES = 'CHANGE_ROLES',
    CREATE_USER = 'CREATE_USER',
    DELETE_USER = 'DELETE_USER',

    CHANGE_ROOM_STATUS = 'CHANGE_ROOM_STATUS',
    CLOSE_ROOM = 'CLOSE_ROOM',
    CREATE_ROOM= 'CREATE_ROOM',
    GET_ROOM_LIST = 'GET_ROOM_LIST',
    JOIN_ROOM = 'JOIN_ROOM',
    LEAVE_ROOM = 'LEAVE_ROOM',
    VOTE = 'VOTE'

}
